version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: nextgencup
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1231
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - nextgencup-net

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=/app:$PYTHONPATH
    restart: always
    depends_on:
      - db
      - mock-api
    volumes:
      - .:/app
    networks:
      - nextgencup-net
    extra_hosts:
      - "auth.challengermode.com:172.29.0.2"  

  api:
    build:
      context: ./web_api_service
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mock-api
    volumes:
      - .:/app
    networks:
      - nextgencup-net

  web:
    build: ./web_service
    ports:
      - "3000:80"
    restart: always
    networks:
      - nextgencup-net

  mock-api:
    build: ./mock_challengermode
    ports:
      - "8081:80"
    networks:
      - nextgencup-net

volumes:
  pgdata:

networks:
  nextgencup-net:
    driver: bridge
