version: "3.9"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: nextgencup
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1231
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - backend

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=/app:$PYTHONPATH
    restart: always
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - backend

  web:
    build: ./web_service
    ports:
      - "3000:80"
    restart: always
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
