version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build: .
    environment:
      - PYTHONPATH=/app:$PYTHONPATH
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./bot_service:/app/bot_service

  web:
    build: ./web_service
    ports:
      - "3000:80"  # Хост:Контейнер (Nginx)
    restart: always

volumes:
  pgdata:
