version: '3.8'
services:
  db:
    image: postgres:16
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nextgencup-net

  mock-api:
    build: ./mock_challengermode
    ports:
      - "8081:80"
    networks:
      - nextgencup-net

  api:
    build:
      context: .
      dockerfile: web_api_service/Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - BOT_TOKEN=${BOT_TOKEN}
    depends_on:
      - db
      - mock-api
    networks:
      - nextgencup-net

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - mock-api
    networks:
      - nextgencup-net
    volumes:
      - .:/app

  web:
    build: ./web_service
    ports:
      - "3000:80"
    networks:
      - nextgencup-net

volumes:
  pgdata:

networks:
  nextgencup-net:
    driver: bridge
