services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@yandex.ru
      PGADMIN_DEFAULT_PASSWORD: admin@admin!
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - backend

  bot:
    build: .
    environment:
      - PYTHONPATH=/app:$PYTHONPATH
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./bot_service:/app/bot_service
    networks:
      - backend

  web:
    build: ./web_service
    ports:
      - "3000:80"
    restart: always
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
