version: '3.9'

services:
  db:
    image: postgres:13
    container_name: db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1231"
      POSTGRES_DB: nextgencup
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  bot:
    build:
      context: ./bot_service
      dockerfile: Dockerfile 
    container_name: bot_service
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: "1231"
      DB_NAME: nextgencup
    volumes:
      - ./bot_service:/app
    command: python main.py

  web:
    build:
      context: ./web-service
      dockerfile: Dockerfile
    container_name: web-service
    ports:
      - "3000:3000"
    volumes:
      - ./web-service:/app
    command: npm start
